import { Staff } from "@/features/staff/types";

export const mockStaff: Staff[] = [
  {
    id: "STAFF-001",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1001",
    firstName: "Mawuli",
    lastName: "Agbenyega",
    rank: "Head of School",
    systemRole: "Admin",
    division: null,
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000001",
    email: "m.agbenyega@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-002",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1002",
    firstName: "Dzifa",
    lastName: "Adzogenu",
    rank: "Deputy Head",
    systemRole: "DeputyHead",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000002",
    email: "d.adzogenu@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-003",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1003",
    firstName: "Kodzo",
    lastName: "Mensah",
    rank: "Deputy Head",
    systemRole: "DeputyHead",
    division: "Lower Primary",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000003",
    email: "k.mensah@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-004",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1141",
    firstName: "Akpene",
    lastName: "Kpodo",
    rank: "Senior Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: true,
    unitHeadOf: "JHS",
    photoUrl: null,
    phone: "0244000004",
    email: "a.kpodo@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-005",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1005",
    firstName: "Selorm",
    lastName: "Tornu",
    rank: "Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000005",
    email: "s.tornu@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-006",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1006",
    firstName: "Senanu",
    lastName: "Awadzi",
    rank: "Class Teacher",
    systemRole: "Teacher",
    division: "Upper Primary",
    isUnitHead: true,
    unitHeadOf: "Upper Primary",
    photoUrl: null,
    phone: "0244000006",
    email: "s.awadzi@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-007",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1007",
    firstName: "Akorfa",
    lastName: "Doe",
    rank: "Deputy Head",
    systemRole: "DeputyHead",
    division: "KG",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000007",
    email: "a.doe@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-008",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1008",
    firstName: "Edem",
    lastName: "Bansa",
    rank: "Senior Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000008",
    email: "e.bansa@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-009",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1009",
    firstName: "Sena",
    lastName: "Hodzi",
    rank: "Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000009",
    email: "s.hodzi@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-010",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1010",
    firstName: "Mawunya",
    lastName: "Ametefe",
    rank: "Class Teacher",
    systemRole: "Teacher",
    division: "Lower Primary",
    isUnitHead: true,
    unitHeadOf: "Lower Primary",
    photoUrl: null,
    phone: "0244000010",
    email: "m.ametefe@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-011",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1011",
    firstName: "Senyo",
    lastName: "Tagoe",
    rank: "Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000011",
    email: "s.tagoe@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-012",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1012",
    firstName: "Selasi",
    lastName: "Yevu",
    rank: "Class Teacher",
    systemRole: "Teacher",
    division: "KG",
    isUnitHead: true,
    unitHeadOf: "KG",
    photoUrl: null,
    phone: "0244000012",
    email: "s.yevu@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-013",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1013",
    firstName: "Eli",
    lastName: "Adigbli",
    rank: "Teacher",
    systemRole: "Teacher",
    division: "Lower Primary",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000013",
    email: "e.adigbli@uhas.edu.gh",
    isActive: false,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-014",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1014",
    firstName: "Afi",
    lastName: "Klutse",
    rank: "Class Teacher",
    systemRole: "Teacher",
    division: "KG",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000014",
    email: "a.klutse@uhas.edu.gh",
    isActive: false,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-015",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1015",
    firstName: "Worlanyo",
    lastName: "Gbedemah",
    rank: "Teacher",
    systemRole: "Teacher",
    division: "JHS",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000015",
    email: "w.gbedemah@uhas.edu.gh",
    isActive: false,
    createdAt: "2026-01-05T08:00:00Z",
  },
  {
    id: "STAFF-016",
    schoolId: "school-uhas-001",
    uhasId: "UHAS1016",
    firstName: "Edinam",
    lastName: "Asare",
    rank: "Deputy Head",
    systemRole: "DeputyHead",
    division: "Upper Primary",
    isUnitHead: false,
    unitHeadOf: null,
    photoUrl: null,
    phone: "0244000016",
    email: "e.asare@uhas.edu.gh",
    isActive: true,
    createdAt: "2026-01-05T08:00:00Z",
  },
];
