/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 when the process is up. Used by Railway + load-balancer probes.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * HealthResponse
         * @description Liveness response — the minimum a load balancer needs.
         *
         *     Returned by `GET /health`. Keep this stable; deploy infra depends
         *     on the shape never breaking.
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' when the process is serving.
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @description Human-readable service name.
             */
            service: string;
            /**
             * Version
             * @description Package version from pyproject.toml.
             */
            version: string;
            /**
             * Env
             * @description Deployment environment label.
             */
            env: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
