/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness check
         * @description Returns 200 when the process is up. Used by Railway + load-balancer probes.
         */
        get: operations["get_health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/school": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Fetch the current school's settings
         * @description Return the full settings row for the caller's school.
         *
         *     Any authenticated user with a valid school_id claim can read this —
         *     the settings drive UI everywhere (logo on every page, term on the
         *     dashboard, brand colours), not just the Admin Settings page.
         */
        get: operations["get_school_school_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update school settings (Admin only)
         * @description Apply a partial update; writes an audit_log row with the diff.
         *
         *     Only `Admin` can modify settings. The audit row records who, when,
         *     and the field-level before/after — same shape as the legacy
         *     `SCHOOL_SETTINGS_UPDATE` rows produced by the Next-side Server
         *     Action, so historical entries remain queryable.
         */
        patch: operations["patch_school_school_patch"];
        trace?: never;
    };
    "/school/terms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List all terms for the current school
         * @description Return every configured term row, sorted (academic_year, term).
         */
        get: operations["list_terms_school_terms_get"];
        /**
         * Upsert the three terms for one academic year (Admin only)
         * @description Replace all three terms for the given academic_year in one call.
         *
         *     Schema-level validators already enforced "exactly 3 distinct terms
         *     numbered 1/2/3, end ≥ start". The service walks the batch, upserts
         *     by natural key (school, year, term), and writes a single audit row.
         */
        put: operations["upsert_terms_school_terms_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Staff */
        get: operations["list_staff_staff_get"];
        put?: never;
        /** Create Staff */
        post: operations["create_staff_staff_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Staff */
        get: operations["get_staff_staff__staff_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Staff */
        patch: operations["update_staff_staff__staff_id__patch"];
        trace?: never;
    };
    "/staff/{staff_id}/role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Role */
        patch: operations["change_role_staff__staff_id__role_patch"];
        trace?: never;
    };
    "/staff/{staff_id}/unit-head": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Toggle Unit Head */
        patch: operations["toggle_unit_head_staff__staff_id__unit_head_patch"];
        trace?: never;
    };
    "/staff/{staff_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Staff */
        post: operations["activate_staff_staff__staff_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/staff/{staff_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Staff */
        post: operations["deactivate_staff_staff__staff_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardians": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Guardians */
        get: operations["list_guardians_guardians_get"];
        put?: never;
        /** Create Guardian */
        post: operations["create_guardian_guardians_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/guardians/{guardian_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Guardian */
        get: operations["get_guardian_guardians__guardian_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Guardian */
        patch: operations["update_guardian_guardians__guardian_id__patch"];
        trace?: never;
    };
    "/students": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Students */
        get: operations["list_students_students_get"];
        put?: never;
        /** Create Student */
        post: operations["create_student_students_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Student */
        get: operations["get_student_students__student_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Student */
        patch: operations["update_student_students__student_id__patch"];
        trace?: never;
    };
    "/students/{student_id}/activate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate Student */
        post: operations["activate_student_students__student_id__activate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/students/{student_id}/deactivate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Deactivate Student */
        post: operations["deactivate_student_students__student_id__deactivate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Subjects */
        get: operations["list_subjects_subjects_get"];
        put?: never;
        /** Create Subject */
        post: operations["create_subject_subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Subject */
        get: operations["get_subject_subjects__subject_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Subject */
        patch: operations["update_subject_subjects__subject_id__patch"];
        trace?: never;
    };
    "/classes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Classes */
        get: operations["list_classes_classes_get"];
        put?: never;
        /** Create Class */
        post: operations["create_class_classes_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{class_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Class */
        get: operations["get_class_classes__class_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Class */
        patch: operations["update_class_classes__class_id__patch"];
        trace?: never;
    };
    "/classes/{class_id}/subjects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Class Subjects */
        get: operations["list_class_subjects_classes__class_id__subjects_get"];
        put?: never;
        /** Assign Class Subject */
        post: operations["assign_class_subject_classes__class_id__subjects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{class_id}/subjects/{subject_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Class Subject */
        delete: operations["remove_class_subject_classes__class_id__subjects__subject_id__delete"];
        options?: never;
        head?: never;
        /** Set Class Subject Teacher */
        patch: operations["set_class_subject_teacher_classes__class_id__subjects__subject_id__patch"];
        trace?: never;
    };
    "/classes/{class_id}/teachers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Class Teachers */
        get: operations["list_class_teachers_classes__class_id__teachers_get"];
        put?: never;
        /** Assign Class Teacher */
        post: operations["assign_class_teacher_classes__class_id__teachers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{class_id}/teachers/{staff_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove Class Teacher */
        delete: operations["remove_class_teacher_classes__class_id__teachers__staff_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Enroll Student */
        post: operations["enroll_student_enrollments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/enrollments/{enrollment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Enrollment */
        get: operations["get_enrollment_enrollments__enrollment_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Change Enrollment Status */
        patch: operations["change_enrollment_status_enrollments__enrollment_id__patch"];
        trace?: never;
    };
    "/students/{student_id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Student Enrollments */
        get: operations["list_student_enrollments_students__student_id__enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/classes/{class_id}/enrollments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Class Enrollments */
        get: operations["list_class_enrollments_classes__class_id__enrollments_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * ClassCreate
         * @description Client passes a canonical slug; service uppercases + validates uniqueness.
         */
        ClassCreate: {
            /** Name */
            name: string;
            /**
             * Division
             * @enum {string}
             */
            division: "KG" | "Lower Primary" | "Upper Primary" | "JHS";
            /** Academicyear */
            academicYear: string;
            /** Slug */
            slug: string;
        };
        /** ClassRead */
        ClassRead: {
            /** Name */
            name: string;
            /**
             * Division
             * @enum {string}
             */
            division: "KG" | "Lower Primary" | "Upper Primary" | "JHS";
            /** Academicyear */
            academicYear: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
            /**
             * Studentcount
             * @default 0
             */
            studentCount: number | null;
            /** Primaryteachername */
            primaryTeacherName?: string | null;
        };
        /**
         * ClassSubjectAssignRequest
         * @description `POST /classes/{class_id}/subjects` — assign a subject (opt. teacher).
         */
        ClassSubjectAssignRequest: {
            /**
             * Subjectid
             * Format: uuid
             */
            subjectId: string;
            /** Teacherid */
            teacherId?: string | null;
        };
        /**
         * ClassSubjectRead
         * @description A row of `class_subjects` — the joined subject + optional teacher name.
         *
         *     The frontend renders the class detail page from this shape; the
         *     embedded `subjectName` / `teacherName` save it a second round trip.
         */
        ClassSubjectRead: {
            /**
             * Classid
             * Format: uuid
             */
            classId: string;
            /**
             * Subjectid
             * Format: uuid
             */
            subjectId: string;
            /** Subjectslug */
            subjectSlug: string;
            /** Subjectname */
            subjectName: string;
            /** Teacherid */
            teacherId?: string | null;
            /** Teacherfirstname */
            teacherFirstName?: string | null;
            /** Teacherlastname */
            teacherLastName?: string | null;
        };
        /**
         * ClassSubjectTeacherUpdate
         * @description `PATCH /classes/{class_id}/subjects/{subject_id}` — set/unset teacher.
         *
         *     Pass `teacherId: null` to unassign; a missing key is treated as a
         *     no-op (uses `exclude_unset`).
         */
        ClassSubjectTeacherUpdate: {
            /** Teacherid */
            teacherId?: string | null;
        };
        /**
         * ClassSubjectsListResponse
         * @description Non-paged wrapper — a class has at most ~10 subjects.
         */
        ClassSubjectsListResponse: {
            /** Items */
            items: components["schemas"]["ClassSubjectRead"][];
        };
        /** ClassTeacherAssignRequest */
        ClassTeacherAssignRequest: {
            /**
             * Staffid
             * Format: uuid
             */
            staffId: string;
            /**
             * Isprimary
             * @default false
             */
            isPrimary: boolean;
        };
        /**
         * ClassTeacherRead
         * @description A row of `class_teachers` with embedded staff name.
         */
        ClassTeacherRead: {
            /**
             * Classid
             * Format: uuid
             */
            classId: string;
            /**
             * Staffid
             * Format: uuid
             */
            staffId: string;
            /** Stafffirstname */
            staffFirstName: string;
            /** Stafflastname */
            staffLastName: string;
            /** Isprimary */
            isPrimary: boolean;
        };
        /**
         * ClassTeachersListResponse
         * @description Non-paged wrapper — small list.
         */
        ClassTeachersListResponse: {
            /** Items */
            items: components["schemas"]["ClassTeacherRead"][];
        };
        /** ClassUpdate */
        ClassUpdate: {
            /** Name */
            name?: string | null;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
        };
        /**
         * ClassesListResponse
         * @description Paged class list. See `app.core.pagination.Paginated`.
         */
        ClassesListResponse: {
            /** Items */
            items: components["schemas"]["ClassRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * EnrollmentCreate
         * @description `POST /enrollments` — enrol an existing student into a class.
         *
         *     Doesn't take `academicYear`; server reads it from the school's
         *     current config (single source of truth for what "this year" means).
         */
        EnrollmentCreate: {
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /**
             * Classid
             * Format: uuid
             */
            classId: string;
        };
        /**
         * EnrollmentRead
         * @description Read shape — joined class + student fields for display.
         *
         *     The class name / student name / photo url come from LEFT JOINs in
         *     the list query so the roster + student-history UIs render without
         *     a second lookup per row.
         */
        EnrollmentRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Studentid
             * Format: uuid
             */
            studentId: string;
            /**
             * Classid
             * Format: uuid
             */
            classId: string;
            /** Classname */
            className?: string | null;
            /** Division */
            division?: string | null;
            /** Academicyear */
            academicYear: string;
            /**
             * Status
             * @enum {string}
             */
            status: "Active" | "Repeating" | "Withdrawn";
            /**
             * Enrollmentdate
             * Format: date
             */
            enrollmentDate: string;
            /** Studentslug */
            studentSlug?: string | null;
            /** Studentfirstname */
            studentFirstName?: string | null;
            /** Studentlastname */
            studentLastName?: string | null;
            /** Studentgender */
            studentGender?: string | null;
            /** Studentphotourl */
            studentPhotoUrl?: string | null;
            /** Studentisactive */
            studentIsActive?: boolean | null;
        };
        /**
         * EnrollmentStatusUpdate
         * @description `PATCH /enrollments/{id}` — narrow endpoint just for status changes.
         *
         *     Uses `Field(...)` (required) — no partial-update semantics; the
         *     caller states the target status explicitly. Promotion + transfer
         *     flows drive this.
         */
        EnrollmentStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "Active" | "Repeating" | "Withdrawn";
        };
        /**
         * EnrollmentsListResponse
         * @description Paged enrollments list. See `app.core.pagination.Paginated`.
         */
        EnrollmentsListResponse: {
            /** Items */
            items: components["schemas"]["EnrollmentRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * GradingBand
         * @description One row in the school's grading-band table.
         *
         *     Boundaries are inclusive on both ends; the score ranges are
         *     consecutive and cover 0-100 without gaps.
         */
        GradingBand: {
            /** Min */
            min: number;
            /** Max */
            max: number;
            /** Grade */
            grade: string;
            /** Interpretation */
            interpretation: string;
        };
        /** GuardianCreate */
        GuardianCreate: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /** GuardianRead */
        GuardianRead: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
        };
        /** GuardianUpdate */
        GuardianUpdate: {
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Email */
            email?: string | null;
            /** Phone */
            phone?: string | null;
        };
        /**
         * GuardiansListResponse
         * @description Paged guardian list. See `app.core.pagination.Paginated`.
         */
        GuardiansListResponse: {
            /** Items */
            items: components["schemas"]["GuardianRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthResponse
         * @description Liveness response — the minimum a load balancer needs.
         *
         *     Returned by `GET /health`. Keep this stable; deploy infra depends
         *     on the shape never breaking.
         */
        HealthResponse: {
            /**
             * Status
             * @description Always 'ok' when the process is serving.
             * @constant
             */
            status: "ok";
            /**
             * Service
             * @description Human-readable service name.
             */
            service: string;
            /**
             * Version
             * @description Package version from pyproject.toml.
             */
            version: string;
            /**
             * Env
             * @description Deployment environment label.
             */
            env: string;
        };
        /**
         * NotificationDefaults
         * @description Which event categories trigger an in-app + email notification by default.
         */
        NotificationDefaults: {
            /** Onlessonplanrejected */
            onLessonPlanRejected: boolean;
            /** Onannouncementposted */
            onAnnouncementPosted: boolean;
            /** Onresultspublished */
            onResultsPublished: boolean;
        };
        /**
         * SchoolRead
         * @description Outbound response shape — full school settings.
         *
         *     Includes server-set fields (`id`, `slug`, `is_active`, `created_at`)
         *     on top of the editable `Base` shape. `from_attributes=True` lets
         *     routers validate ORM rows directly:
         *
         *         return SchoolRead.model_validate(school_orm_row)
         *
         *     `id` is the uuid PK; `slug` is the human-readable identifier
         *     ("uhas-basic") for URLs + audit-log readability. Pydantic
         *     serialises UUID as ISO-string in JSON; the frontend treats it as
         *     an opaque string.
         */
        SchoolRead: {
            /** Name */
            name: string;
            /** Motto */
            motto?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Principalname */
            principalName?: string | null;
            /** Logourl */
            logoUrl?: string | null;
            /** Academicyear */
            academicYear: string;
            /** Currentterm */
            currentTerm: number;
            /**
             * Gradingscale
             * @default GES_STANDARD
             * @enum {string}
             */
            gradingScale: "GES_STANDARD" | "CUSTOM";
            /** Gradingbands */
            gradingBands?: components["schemas"]["GradingBand"][] | null;
            scoreWeights?: components["schemas"]["ScoreWeights"] | null;
            /**
             * Passmark
             * @default 40
             */
            passMark: number;
            /** Emailfromname */
            emailFromName?: string | null;
            /** Emailreplyto */
            emailReplyTo?: string | null;
            notificationDefaults?: components["schemas"]["NotificationDefaults"] | null;
            /**
             * Sessiontimeoutminutes
             * @default 480
             */
            sessionTimeoutMinutes: number;
            /**
             * Passwordminlength
             * @default 8
             */
            passwordMinLength: number;
            /**
             * Forcepasswordchangeonfirstlogin
             * @default true
             */
            forcePasswordChangeOnFirstLogin: boolean;
            /**
             * Defaultcolorscheme
             * @default uhas
             * @enum {string}
             */
            defaultColorScheme: "default" | "uhas";
            /** Sidebaraccenthex */
            sidebarAccentHex?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Isactive
             * @default true
             */
            isActive: boolean;
            /** Createdat */
            createdAt?: string | null;
        };
        /**
         * SchoolUpdate
         * @description Partial update payload for `PATCH /school`.
         *
         *     All fields optional — clients send only what's changing. The router
         *     builds the audit-log diff from the subset of fields actually present
         *     in the parsed model.
         *
         *     Doesn't inherit `SchoolBase` — Update's all-optional shape can't
         *     compose cleanly with Base's required fields.
         *
         *     `model_config(extra='forbid')` rejects unknown fields so a typo on
         *     the client never silently no-ops.
         */
        SchoolUpdate: {
            /** Name */
            name?: string | null;
            /** Motto */
            motto?: string | null;
            /** Address */
            address?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Principalname */
            principalName?: string | null;
            /** Logourl */
            logoUrl?: string | null;
            /** Academicyear */
            academicYear?: string | null;
            /** Currentterm */
            currentTerm?: number | null;
            /** Gradingscale */
            gradingScale?: ("GES_STANDARD" | "CUSTOM") | null;
            /** Gradingbands */
            gradingBands?: components["schemas"]["GradingBand"][] | null;
            scoreWeights?: components["schemas"]["ScoreWeights"] | null;
            /** Passmark */
            passMark?: number | null;
            /** Emailfromname */
            emailFromName?: string | null;
            /** Emailreplyto */
            emailReplyTo?: string | null;
            notificationDefaults?: components["schemas"]["NotificationDefaults"] | null;
            /** Sessiontimeoutminutes */
            sessionTimeoutMinutes?: number | null;
            /** Passwordminlength */
            passwordMinLength?: number | null;
            /** Forcepasswordchangeonfirstlogin */
            forcePasswordChangeOnFirstLogin?: boolean | null;
            /** Defaultcolorscheme */
            defaultColorScheme?: ("default" | "uhas") | null;
            /** Sidebaraccenthex */
            sidebarAccentHex?: string | null;
        };
        /**
         * ScoreWeights
         * @description Mid-term + end-of-term score weighting. Must sum to 100.
         */
        ScoreWeights: {
            /** Exam */
            exam: number;
            /** Cat1 */
            cat1: number;
            /** Cat2 */
            cat2: number;
            /** Groupwork */
            groupWork: number;
            /** Projectwork */
            projectWork: number;
        };
        /**
         * StaffCreate
         * @description Inbound payload for `POST /staff`.
         *
         *     `system_role` is required on create (different from `StaffBase`
         *     where it's optional for partial reads); the service enforces that
         *     non-Admin roles also supply a `division`.
         */
        StaffCreate: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Rank */
            rank?: string | null;
            /**
             * Systemrole
             * @enum {string}
             */
            systemRole: "Admin" | "DeputyHead" | "Teacher" | "Accountant";
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /**
             * Isunithead
             * @default false
             */
            isUnitHead: boolean | null;
            /** Unitheadof */
            unitHeadOf?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /** Uhasid */
            uhasId?: string | null;
            /** Phone */
            phone?: string | null;
            /**
             * Email
             * Format: email
             */
            email: string;
            /** Photourl */
            photoUrl?: string | null;
        };
        /**
         * StaffListResponse
         * @description Paged staff list. See `app.core.pagination.Paginated` for the envelope.
         */
        StaffListResponse: {
            /** Items */
            items: components["schemas"]["StaffRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * StaffRead
         * @description Outbound shape — everything plus the server-managed fields.
         */
        StaffRead: {
            /** Firstname */
            firstName: string;
            /** Lastname */
            lastName: string;
            /** Rank */
            rank?: string | null;
            /** Systemrole */
            systemRole?: ("Admin" | "DeputyHead" | "Teacher" | "Accountant") | null;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /**
             * Isunithead
             * @default false
             */
            isUnitHead: boolean | null;
            /** Unitheadof */
            unitHeadOf?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /** Uhasid */
            uhasId?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Photourl */
            photoUrl?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
            /**
             * Isactive
             * @default true
             */
            isActive: boolean | null;
            /** Createdat */
            createdAt?: string | null;
        };
        /**
         * StaffRoleChange
         * @description `PATCH /staff/{id}/role` payload.
         *
         *     Role changes are tracked in audit_log; kept distinct from `StaffUpdate`
         *     so the audit hook only fires for actual role moves.
         */
        StaffRoleChange: {
            /**
             * Systemrole
             * @enum {string}
             */
            systemRole: "Admin" | "DeputyHead" | "Teacher" | "Accountant";
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
        };
        /**
         * StaffUnitHeadToggle
         * @description `PATCH /staff/{id}/unit-head` payload.
         */
        StaffUnitHeadToggle: {
            /** Isunithead */
            isUnitHead: boolean;
            /** Unitheadof */
            unitHeadOf?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
        };
        /**
         * StaffUpdate
         * @description Partial update for `PATCH /staff/{id}`.
         *
         *     Every field optional — only present fields are written.
         */
        StaffUpdate: {
            /** Firstname */
            firstName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Rank */
            rank?: string | null;
            /** Uhasid */
            uhasId?: string | null;
            /** Phone */
            phone?: string | null;
            /** Email */
            email?: string | null;
            /** Photourl */
            photoUrl?: string | null;
        };
        /**
         * StudentCreate
         * @description Inbound payload for `POST /students`.
         *
         *     `class_id` triggers the initial Enrollment row. `dob` and `gender`
         *     are required on create (the report card needs them) even though
         *     they're optional in `StudentBase` for read-shape flexibility.
         */
        StudentCreate: {
            /** Firstname */
            firstName: string;
            /** Middlename */
            middleName?: string | null;
            /** Lastname */
            lastName: string;
            /**
             * Dob
             * Format: date
             */
            dob: string;
            /**
             * Gender
             * @enum {string}
             */
            gender: "Male" | "Female";
            /** Photourl */
            photoUrl?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Religion */
            religion?: string | null;
            /**
             * Classid
             * Format: uuid
             */
            classId: string;
        };
        /**
         * StudentRead
         * @description Read shape — student row + the joined current-year enrollment.
         *
         *     `class_id` / `class_name` / `division` come from the enrollments
         *     table. They're `None` for students who have no active enrollment
         *     in the current academic year (inactive students, mid-promotion).
         */
        StudentRead: {
            /** Firstname */
            firstName: string;
            /** Middlename */
            middleName?: string | null;
            /** Lastname */
            lastName: string;
            /** Dob */
            dob?: string | null;
            /** Gender */
            gender?: ("Male" | "Female") | null;
            /** Photourl */
            photoUrl?: string | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Religion */
            religion?: string | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
            /**
             * Isactive
             * @default true
             */
            isActive: boolean | null;
            /** Createdat */
            createdAt?: string | null;
            /** Classid */
            classId?: string | null;
            /** Classname */
            className?: string | null;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
        };
        /** StudentUpdate */
        StudentUpdate: {
            /** Firstname */
            firstName?: string | null;
            /** Middlename */
            middleName?: string | null;
            /** Lastname */
            lastName?: string | null;
            /** Dob */
            dob?: string | null;
            /** Gender */
            gender?: ("Male" | "Female") | null;
            /** Phone */
            phone?: string | null;
            /** Address */
            address?: string | null;
            /** Nationality */
            nationality?: string | null;
            /** Religion */
            religion?: string | null;
            /** Photourl */
            photoUrl?: string | null;
        };
        /**
         * StudentsListResponse
         * @description Paged student list. See `app.core.pagination.Paginated`.
         */
        StudentsListResponse: {
            /** Items */
            items: components["schemas"]["StudentRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * SubjectCreate
         * @description Client-supplied slug is the human-readable code (`MATH`, `ENG`).
         *
         *     Slug is uppercased server-side so the exposed identifier stays
         *     canonical regardless of what the caller sent.
         */
        SubjectCreate: {
            /** Name */
            name: string;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /**
             * Category
             * @default Core
             */
            category: ("Core" | "Elective" | "Optional") | null;
            /** Slug */
            slug: string;
        };
        /** SubjectRead */
        SubjectRead: {
            /** Name */
            name: string;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /**
             * Category
             * @default Core
             */
            category: ("Core" | "Elective" | "Optional") | null;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Slug */
            slug: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
        };
        /** SubjectUpdate */
        SubjectUpdate: {
            /** Name */
            name?: string | null;
            /** Division */
            division?: ("KG" | "Lower Primary" | "Upper Primary" | "JHS") | null;
            /** Category */
            category?: ("Core" | "Elective" | "Optional") | null;
        };
        /**
         * SubjectsListResponse
         * @description Paged subject list. See `app.core.pagination.Paginated`.
         */
        SubjectsListResponse: {
            /** Items */
            items: components["schemas"]["SubjectRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Size */
            size: number;
        };
        /**
         * TermInput
         * @description One row in the upsert payload — no id (server upserts by natural key).
         */
        TermInput: {
            /** Term */
            term: number;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
        };
        /**
         * TermRead
         * @description Outbound representation of a single school_terms row.
         */
        TermRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Schoolid
             * Format: uuid
             */
            schoolId: string;
            /** Academicyear */
            academicYear: string;
            /** Term */
            term: number;
            /**
             * Startdate
             * Format: date
             */
            startDate: string;
            /**
             * Enddate
             * Format: date
             */
            endDate: string;
        };
        /**
         * TermsListResponse
         * @description Wrapper for `GET /school/terms` — keeps room for future metadata
         *     (counts, last-updated timestamps) without breaking the wire format.
         */
        TermsListResponse: {
            /** Items */
            items: components["schemas"]["TermRead"][];
        };
        /**
         * TermsUpsertRequest
         * @description Payload for `PUT /school/terms` — replaces all 3 terms for a year.
         *
         *     The Calendar tab edits all three terms as one unit of work, so the
         *     API mirrors that: send the full set, server upserts atomically.
         */
        TermsUpsertRequest: {
            /** Academicyear */
            academicYear: string;
            /** Terms */
            terms: components["schemas"]["TermInput"][];
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    get_school_school_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_school_school_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SchoolUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SchoolRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_terms_school_terms_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upsert_terms_school_terms_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TermsUpsertRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TermsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_staff_staff_get: {
        parameters: {
            query?: {
                /** @description Search across name + email + UHAS ID */
                q?: string | null;
                /** @description 1-based page index */
                page?: number;
                /** @description Rows per page */
                size?: number;
                activeOnly?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_staff_staff_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_staff_staff__staff_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_staff_staff__staff_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_role_staff__staff_id__role_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffRoleChange"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    toggle_unit_head_staff__staff_id__unit_head_patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StaffUnitHeadToggle"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_staff_staff__staff_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_staff_staff__staff_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StaffRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_guardians_guardians_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardiansListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_guardian_guardians_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardianCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_guardian_guardians__guardian_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                guardian_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_guardian_guardians__guardian_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                guardian_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuardianUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GuardianRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_students_students_get: {
        parameters: {
            query?: {
                q?: string | null;
                page?: number;
                size?: number;
                division?: string | null;
                activeOnly?: boolean;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_student_students_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_student_students__student_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_student_students__student_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StudentUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    activate_student_students__student_id__activate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    deactivate_student_students__student_id__deactivate_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StudentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_subjects_subjects_get: {
        parameters: {
            query?: {
                q?: string | null;
                division?: string | null;
                page?: number;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_subject_subjects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_subject_subjects__subject_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_subject_subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_classes_classes_get: {
        parameters: {
            query?: {
                q?: string | null;
                division?: string | null;
                academicYear?: string | null;
                page?: number;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassesListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_class_classes_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_class_classes__class_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_class_classes__class_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_class_subjects_classes__class_id__subjects_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubjectsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_class_subject_classes__class_id__subjects_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassSubjectAssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_class_subject_classes__class_id__subjects__subject_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_class_subject_teacher_classes__class_id__subjects__subject_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
                subject_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassSubjectTeacherUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassSubjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_class_teachers_classes__class_id__teachers_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassTeachersListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assign_class_teacher_classes__class_id__teachers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ClassTeacherAssignRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClassTeacherRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    remove_class_teacher_classes__class_id__teachers__staff_id__delete: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
                staff_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    enroll_student_enrollments_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_enrollment_enrollments__enrollment_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    change_enrollment_status_enrollments__enrollment_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                enrollment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnrollmentStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_student_enrollments_students__student_id__enrollments_get: {
        parameters: {
            query?: {
                page?: number;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                student_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_class_enrollments_classes__class_id__enrollments_get: {
        parameters: {
            query?: {
                status?: string | null;
                page?: number;
                size?: number;
            };
            header?: {
                authorization?: string | null;
            };
            path: {
                class_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnrollmentsListResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
