import {
  pgTable,
  varchar,
  integer,
  boolean,
  timestamp,
  date,
  text,
  jsonb,
  uuid,
  primaryKey,
  unique,
  index,
} from "drizzle-orm/pg-core";
import { relations } from "drizzle-orm";

// Primary-key convention:
//
//   id      uuid PRIMARY KEY DEFAULT gen_random_uuid()
//   slug    varchar UNIQUE (per school, except schools.slug which is global)
//
// FKs across the schema use uuid → uuid. The slug column lives only on
// tables where humans need a stable readable identifier — schools,
// staff, students, guardians, classes, subjects. Everything else uses
// the UUID alone.
//
// Slugs in seed fixtures retain their historical shape (`STAFF-001`,
// `UHAS-2026-0001`, `class-jhs1`, `uhas-basic`) so audit-log entries
// stay grep-friendly during incident response.
//
// Runtime row-creation lets the DB default the UUID — feature actions
// must NOT generate their own ids via template literals anymore.

// ─── Multi-Tenancy Anchor ────────────────────────────────────────────────────

export const schools = pgTable("schools", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Globally-unique URL-routable slug, e.g. "uhas-basic".
  slug: varchar("slug", { length: 64 }).notNull().unique(),
  name: varchar("name", { length: 255 }).notNull(),
  academicYear: varchar("academic_year", { length: 9 }).notNull(),
  currentTerm: integer("current_term").notNull().default(1),
  gradingScale: varchar("grading_scale", { length: 50 }).default("GES_STANDARD"),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),

  // ── Identity (Admin Settings → Identity tab) ─────────────────────────────
  motto: varchar("motto", { length: 255 }),
  address: text("address"),
  phone: varchar("phone", { length: 50 }),
  email: varchar("email", { length: 255 }),
  principalName: varchar("principal_name", { length: 255 }),
  logoUrl: varchar("logo_url", { length: 500 }),

  // ── Grading (Admin Settings → Grading tab) ───────────────────────────────
  gradingBands: jsonb("grading_bands"),
  scoreWeights: jsonb("score_weights"),
  passMark: integer("pass_mark").default(40),

  // ── Communication defaults (Admin Settings → Communication tab) ──────────
  emailFromName: varchar("email_from_name", { length: 255 }),
  emailReplyTo: varchar("email_reply_to", { length: 255 }),
  notificationDefaults: jsonb("notification_defaults"),

  // ── Security (Admin Settings → Security tab) ─────────────────────────────
  sessionTimeoutMinutes: integer("session_timeout_minutes").default(480),
  passwordMinLength: integer("password_min_length").default(8),
  forcePasswordChangeOnFirstLogin: boolean("force_password_change_on_first_login").default(true),

  // ── Branding (Admin Settings → Branding tab) ─────────────────────────────
  defaultColorScheme: varchar("default_color_scheme", { length: 20 }).default("uhas"),
  sidebarAccentHex: varchar("sidebar_accent_hex", { length: 7 }),
});

export const schoolTerms = pgTable("school_terms", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  academicYear: varchar("academic_year", { length: 9 }).notNull(),
  term: integer("term").notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
}, (t) => ({
  uniqueTerm: unique().on(t.schoolId, t.academicYear, t.term),
}));

// ─── Auth Bridge & RBAC ──────────────────────────────────────────────────────

// users.id MUST equal auth.users.id (Supabase) — set explicitly at insert
// time, never DB-defaulted. The FK to auth.users.id is added in a
// separate migration (Drizzle can't model cross-schema FKs cleanly).
export const users = pgTable(
  "users",
  {
    id: uuid("id").primaryKey(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    email: varchar("email", { length: 255 }).notNull().unique(),
    role: varchar("role", { length: 50 }).notNull(),
    // linkedId points at staff OR guardians depending on role. Polymorphic;
    // resolved per-role at query time. Declared as uuid since both targets
    // are uuid PKs in this revision.
    linkedId: uuid("linked_id"),
    isActive: boolean("is_active").default(true),
    mustChangePassword: boolean("must_change_password").default(true),
  },
  (t) => [
    index("users_linked_id_idx").on(t.linkedId),
  ]
);

// ─── People ──────────────────────────────────────────────────────────────────

export const staff = pgTable("staff", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Per-school readable slug, e.g. STAFF-042. Generated by the service layer.
  slug: varchar("slug", { length: 50 }).notNull(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  uhasId: varchar("uhas_id", { length: 50 }).unique(),
  firstName: varchar("first_name", { length: 255 }).notNull(),
  lastName: varchar("last_name", { length: 255 }).notNull(),
  rank: varchar("rank", { length: 100 }),
  systemRole: varchar("system_role", { length: 50 }),
  division: varchar("division", { length: 50 }),
  isUnitHead: boolean("is_unit_head").default(false),
  unitHeadOf: varchar("unit_head_of", { length: 50 }),
  photoUrl: varchar("photo_url", { length: 500 }),
  phone: varchar("phone", { length: 50 }),
  email: varchar("email", { length: 255 }),
  isActive: boolean("is_active").default(true),
  createdAt: timestamp("created_at").defaultNow(),
}, (t) => [
  unique("staff_school_slug_unique").on(t.schoolId, t.slug),
]);

export const students = pgTable(
  "students",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Per-school readable slug, e.g. UHAS-2026-0001 — appears on report cards.
    slug: varchar("slug", { length: 50 }).notNull(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    firstName: varchar("first_name", { length: 255 }).notNull(),
    middleName: varchar("middle_name", { length: 255 }),
    lastName: varchar("last_name", { length: 255 }).notNull(),
    dob: date("dob"),
    gender: varchar("gender", { length: 10 }),
    photoUrl: varchar("photo_url", { length: 500 }),
    phone: varchar("phone", { length: 50 }),
    address: text("address"),
    nationality: varchar("nationality", { length: 100 }),
    religion: varchar("religion", { length: 100 }),
    isActive: boolean("is_active").default(true),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [
    index("students_school_active_idx").on(t.schoolId, t.isActive),
    unique("students_school_slug_unique").on(t.schoolId, t.slug),
  ]
);

export const guardians = pgTable("guardians", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Per-school readable slug, e.g. GUARDIAN-001.
  slug: varchar("slug", { length: 50 }).notNull(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  firstName: varchar("first_name", { length: 255 }).notNull(),
  lastName: varchar("last_name", { length: 255 }).notNull(),
  // Dual identifier per Phase 1 PR #7 — at least one of email or phone
  // required; the CHECK constraint is added in a separate migration.
  email: varchar("email", { length: 255 }).unique(),
  phone: varchar("phone", { length: 50 }).unique(),
}, (t) => [
  unique("guardians_school_slug_unique").on(t.schoolId, t.slug),
]);

export const studentGuardians = pgTable(
  "student_guardians",
  {
    studentId: uuid("student_id").references(() => students.id).notNull(),
    guardianId: uuid("guardian_id").references(() => guardians.id).notNull(),
    relation: varchar("relation", { length: 50 }),
    isPrimary: boolean("is_primary").default(false),
  },
  (t) => [primaryKey({ columns: [t.studentId, t.guardianId] })]
);

// ─── Academic Structure ──────────────────────────────────────────────────────

export const classes = pgTable(
  "classes",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    // Per-school readable slug, e.g. class-jhs1.
    slug: varchar("slug", { length: 50 }).notNull(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    name: varchar("name", { length: 50 }).notNull(),
    division: varchar("division", { length: 50 }).notNull(),
    academicYear: varchar("academic_year", { length: 9 }).notNull(),
  },
  (t) => [
    index("classes_school_year_idx").on(t.schoolId, t.academicYear),
    unique("classes_school_slug_unique").on(t.schoolId, t.slug),
  ]
);

export const classTeachers = pgTable(
  "class_teachers",
  {
    classId: uuid("class_id").references(() => classes.id).notNull(),
    staffId: uuid("staff_id").references(() => staff.id).notNull(),
    isPrimary: boolean("is_primary").default(false),
  },
  (t) => [primaryKey({ columns: [t.classId, t.staffId] })]
);

export const subjects = pgTable("subjects", {
  id: uuid("id").primaryKey().defaultRandom(),
  // Per-school readable slug / code, e.g. MATH, ENG.
  slug: varchar("slug", { length: 50 }).notNull(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  name: varchar("name", { length: 100 }).notNull(),
  division: varchar("division", { length: 50 }),
  category: varchar("category", { length: 50 }).default("Core"),
}, (t) => [
  unique("subjects_school_slug_unique").on(t.schoolId, t.slug),
]);

export const classSubjects = pgTable(
  "class_subjects",
  {
    classId: uuid("class_id").references(() => classes.id).notNull(),
    subjectId: uuid("subject_id").references(() => subjects.id).notNull(),
    teacherId: uuid("teacher_id").references(() => staff.id),
  },
  (t) => [primaryKey({ columns: [t.classId, t.subjectId] })]
);

export const enrollments = pgTable(
  "enrollments",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    studentId: uuid("student_id").references(() => students.id).notNull(),
    classId: uuid("class_id").references(() => classes.id).notNull(),
    academicYear: varchar("academic_year", { length: 9 }).notNull(),
    status: varchar("status", { length: 50 }).default("Active").notNull(),
    enrollmentDate: date("enrollment_date").notNull(),
  },
  (t) => [
    index("enrollments_student_year_idx").on(t.studentId, t.academicYear),
    index("enrollments_class_idx").on(t.classId),
  ]
);

// ─── Attendance ──────────────────────────────────────────────────────────────

export const attendanceSessions = pgTable(
  "attendance_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    classId: uuid("class_id").references(() => classes.id).notNull(),
    date: date("date").notNull(),
    term: integer("term").notNull(),
    submittedById: uuid("submitted_by_id").references(() => staff.id),
    submittedAt: timestamp("submitted_at").defaultNow(),
  },
  (t) => [
    index("attendance_sessions_class_date_idx").on(t.classId, t.date),
  ]
);

export const attendanceRecords = pgTable(
  "attendance_records",
  {
    sessionId: uuid("session_id").references(() => attendanceSessions.id).notNull(),
    studentId: uuid("student_id").references(() => students.id).notNull(),
    status: varchar("status", { length: 20 }).notNull(),
    lateReason: varchar("late_reason", { length: 255 }),
    note: varchar("note", { length: 255 }),
  },
  (t) => [
    primaryKey({ columns: [t.sessionId, t.studentId] }),
    index("attendance_records_student_idx").on(t.studentId),
  ]
);

// ─── Staff Attendance ───────────────────────────────────────────────────────

export const staffAttendanceSessions = pgTable(
  "staff_attendance_sessions",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    division: varchar("division", { length: 50 }).notNull(),
    date: date("date").notNull(),
    term: integer("term").notNull(),
    submittedById: uuid("submitted_by_id").references(() => staff.id),
    submittedAt: timestamp("submitted_at").defaultNow(),
  },
  (t) => [
    index("staff_attendance_sessions_div_date_idx").on(t.division, t.date),
  ]
);

export const staffAttendanceRecords = pgTable(
  "staff_attendance_records",
  {
    sessionId: uuid("session_id").references(() => staffAttendanceSessions.id).notNull(),
    staffId: uuid("staff_id").references(() => staff.id).notNull(),
    status: varchar("status", { length: 20 }).notNull(),
    note: varchar("note", { length: 255 }),
  },
  (t) => [primaryKey({ columns: [t.sessionId, t.staffId] })]
);

// ─── Leave Requests ──────────────────────────────────────────────────────────

export const leaveRequests = pgTable("leave_requests", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  staffId: uuid("staff_id").references(() => staff.id).notNull(),
  type: varchar("type", { length: 100 }).notNull(),
  startDate: date("start_date").notNull(),
  endDate: date("end_date").notNull(),
  reason: text("reason"),
  status: varchar("status", { length: 50 }).default("pending").notNull(),
  approvedById: uuid("approved_by_id").references(() => staff.id),
  createdAt: timestamp("created_at").defaultNow(),
});

// ─── Academic Planning ───────────────────────────────────────────────────────

export const lessonPlans = pgTable(
  "lesson_plans",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    teacherId: uuid("teacher_id").references(() => staff.id).notNull(),
    subjectId: uuid("subject_id").references(() => subjects.id).notNull(),
    classId: uuid("class_id").references(() => classes.id).notNull(),
    term: integer("term").notNull(),
    week: integer("week").notNull(),
    topic: varchar("topic", { length: 255 }),
    learningObjectives: text("learning_objectives"),
    teachingMethods: text("teaching_methods"),
    resources: text("resources"),
    assessmentPlan: text("assessment_plan"),
    fileUrl: varchar("file_url", { length: 500 }),
    status: varchar("status", { length: 50 }).default("draft").notNull(),
    reviewerComment: text("reviewer_comment"),
    reviewedById: uuid("reviewed_by_id").references(() => staff.id),
    reviewedAt: timestamp("reviewed_at"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
    deletedAt: timestamp("deleted_at"),
  },
  (t) => [
    index("lesson_plans_teacher_status_idx").on(t.teacherId, t.status),
    index("lesson_plans_school_status_idx").on(t.schoolId, t.status),
  ]
);

export const schemes = pgTable("schemes", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  teacherId: uuid("teacher_id").references(() => staff.id).notNull(),
  subjectId: uuid("subject_id").references(() => subjects.id).notNull(),
  classId: uuid("class_id").references(() => classes.id).notNull(),
  type: varchar("type", { length: 20 }).notNull(),
  term: integer("term").notNull(),
  academicYear: varchar("academic_year", { length: 9 }).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  fileUrl: varchar("file_url", { length: 500 }),
  content: text("content"),
  status: varchar("status", { length: 20 }).default("draft").notNull(),
  reviewerComment: text("reviewer_comment"),
  reviewedById: uuid("reviewed_by_id").references(() => staff.id),
  reviewedAt: timestamp("reviewed_at"),
  submittedAt: timestamp("submitted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  deletedAt: timestamp("deleted_at"),
});

// ─── Exams & Scores ──────────────────────────────────────────────────────────

export const exams = pgTable(
  "exams",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    name: varchar("name", { length: 100 }).notNull(),
    type: varchar("type", { length: 50 }).notNull(),
    term: integer("term").notNull(),
    academicYear: varchar("academic_year", { length: 9 }).notNull(),
    isPublished: boolean("is_published").default(false),
    publishedAt: timestamp("published_at"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [
    index("exams_school_year_term_idx").on(t.schoolId, t.academicYear, t.term),
  ]
);

export const scores = pgTable(
  "scores",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    examId: uuid("exam_id").references(() => exams.id).notNull(),
    studentId: uuid("student_id").references(() => students.id).notNull(),
    subjectId: uuid("subject_id").references(() => subjects.id).notNull(),
    cat1: integer("cat1"),
    cat2: integer("cat2"),
    projectWork: integer("project_work"),
    groupWork: integer("group_work"),
    examScore: integer("exam_score"),
    totalScore: integer("total_score"),
    grade: varchar("grade", { length: 5 }),
    interpretation: varchar("interpretation", { length: 50 }),
    subjectPosition: integer("subject_position"),
    createdAt: timestamp("created_at").defaultNow(),
    updatedAt: timestamp("updated_at").defaultNow(),
  },
  (t) => [
    index("scores_exam_subject_idx").on(t.examId, t.subjectId),
    index("scores_student_exam_idx").on(t.studentId, t.examId),
  ]
);

export const classReportSubmissions = pgTable("class_report_submissions", {
  id: uuid("id").primaryKey().defaultRandom(),
  examId: uuid("exam_id").references(() => exams.id).notNull(),
  classId: uuid("class_id").references(() => classes.id).notNull(),
  status: varchar("status", { length: 20 }).default("draft").notNull(),
  submittedById: uuid("submitted_by_id").references(() => staff.id),
  submittedAt: timestamp("submitted_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const studentReportRemarks = pgTable("student_report_remarks", {
  id: uuid("id").primaryKey().defaultRandom(),
  examId: uuid("exam_id").references(() => exams.id).notNull(),
  studentId: uuid("student_id").references(() => students.id).notNull(),
  classTeacherRemark: text("class_teacher_remark"),
  headOfSchoolComment: text("head_of_school_comment"),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const assignments = pgTable("assignments", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  teacherId: uuid("teacher_id").references(() => staff.id).notNull(),
  subjectId: uuid("subject_id").references(() => subjects.id).notNull(),
  classId: uuid("class_id").references(() => classes.id).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  fileUrl: varchar("file_url", { length: 500 }),
  dueDate: date("due_date").notNull(),
  status: varchar("status", { length: 20 }).default("draft").notNull(),
  publishedAt: timestamp("published_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
  deletedAt: timestamp("deleted_at"),
});

// ─── Announcements ───────────────────────────────────────────────────────────

export const announcements = pgTable(
  "announcements",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    body: text("body").notNull(),
    audience: varchar("audience", { length: 100 }).notNull(),
    isCritical: boolean("is_critical").default(false),
    createdById: uuid("created_by_id").references(() => staff.id).notNull(),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [
    index("announcements_school_created_idx").on(t.schoolId, t.createdAt),
  ]
);

// ─── Academic Calendar ───────────────────────────────────────────────────────

export const calendarEvents = pgTable("calendar_events", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  title: varchar("title", { length: 255 }).notNull(),
  description: text("description"),
  startDate: date("start_date").notNull(),
  endDate: date("end_date"),
  type: varchar("type", { length: 20 }).notNull(),
  createdById: uuid("created_by_id").references(() => staff.id).notNull(),
  createdAt: timestamp("created_at").defaultNow(),
});

// ─── Parent-Teacher Appointments ─────────────────────────────────────────────

export const appointments = pgTable("appointments", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  guardianId: uuid("guardian_id").references(() => guardians.id).notNull(),
  studentId: uuid("student_id").references(() => students.id).notNull(),
  teacherId: uuid("teacher_id").references(() => staff.id).notNull(),
  preferredDate: date("preferred_date").notNull(),
  preferredSlot: varchar("preferred_slot", { length: 50 }).notNull(),
  reason: text("reason"),
  status: varchar("status", { length: 20 }).default("pending").notNull(),
  teacherResponse: text("teacher_response"),
  respondedAt: timestamp("responded_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ─── Student Promotion ───────────────────────────────────────────────────────

export const promotionSeasons = pgTable("promotion_seasons", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  academicYear: varchar("academic_year", { length: 9 }).notNull(),
  status: varchar("status", { length: 20 }).default("closed").notNull(),
  openedWithOverride: boolean("opened_with_override").default(false),
  openedById: uuid("opened_by_id").references(() => staff.id),
  openedAt: timestamp("opened_at"),
  closedById: uuid("closed_by_id").references(() => staff.id),
  closedAt: timestamp("closed_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const promotionSubmissions = pgTable("promotion_submissions", {
  id: uuid("id").primaryKey().defaultRandom(),
  schoolId: uuid("school_id").references(() => schools.id).notNull(),
  classId: uuid("class_id").references(() => classes.id).notNull(),
  academicYear: varchar("academic_year", { length: 9 }).notNull(),
  status: varchar("status", { length: 20 }).default("draft").notNull(),
  submittedById: uuid("submitted_by_id").references(() => staff.id),
  submittedAt: timestamp("submitted_at"),
  reviewerComment: text("reviewer_comment"),
  reviewedById: uuid("reviewed_by_id").references(() => staff.id),
  reviewedAt: timestamp("reviewed_at"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

export const promotionDecisions = pgTable("promotion_decisions", {
  id: uuid("id").primaryKey().defaultRandom(),
  submissionId: uuid("submission_id").references(() => promotionSubmissions.id).notNull(),
  studentId: uuid("student_id").references(() => students.id).notNull(),
  decision: varchar("decision", { length: 20 }).notNull(),
  targetClassId: uuid("target_class_id").references(() => classes.id),
  reason: text("reason"),
  suggestedDecision: varchar("suggested_decision", { length: 20 }),
  suggestedReason: text("suggested_reason"),
  failedCoreSubjects: integer("failed_core_subjects"),
  createdAt: timestamp("created_at").defaultNow(),
  updatedAt: timestamp("updated_at").defaultNow(),
});

// ─── Audit Log ───────────────────────────────────────────────────────────────

// `targetId` is intentionally uuid even though target rows live across many
// tables — every PK is uuid now, so the type is consistent. The actor
// (`userId`) is also uuid since it points at users.id.
export const auditLog = pgTable(
  "audit_log",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    userId: uuid("user_id").notNull(),
    action: varchar("action", { length: 100 }).notNull(),
    targetTable: varchar("target_table", { length: 100 }),
    targetId: uuid("target_id"),
    before: text("before"),
    after: text("after"),
    createdAt: timestamp("created_at").defaultNow(),
  },
  (t) => [
    index("audit_log_action_created_idx").on(t.action, t.createdAt),
    index("audit_log_user_idx").on(t.userId),
    index("audit_log_target_idx").on(t.targetTable, t.targetId),
  ]
);

// ─── In-App Notifications ────────────────────────────────────────────────────

export const notifications = pgTable(
  "notifications",
  {
    id: uuid("id").primaryKey().defaultRandom(),
    schoolId: uuid("school_id").references(() => schools.id).notNull(),
    userId: uuid("user_id").references(() => users.id).notNull(),
    kind: varchar("kind", { length: 50 }).notNull(),
    title: varchar("title", { length: 255 }).notNull(),
    body: text("body").notNull(),
    link: varchar("link", { length: 500 }),
    readAt: timestamp("read_at"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
  },
  (t) => ({
    userReadIdx: index("notifications_user_read_idx").on(t.userId, t.readAt),
  })
);

// ─── Relations (Drizzle joins) ───────────────────────────────────────────────

export const usersRelations = relations(users, ({ one }) => ({
  school: one(schools, { fields: [users.schoolId], references: [schools.id] }),
}));

export const staffRelations = relations(staff, ({ one, many }) => ({
  school: one(schools, { fields: [staff.schoolId], references: [schools.id] }),
  lessonPlans: many(lessonPlans),
  schemes: many(schemes),
}));

export const studentsRelations = relations(students, ({ one, many }) => ({
  school: one(schools, { fields: [students.schoolId], references: [schools.id] }),
  enrollments: many(enrollments),
  scores: many(scores),
  attendance: many(attendanceRecords),
}));

export const classesRelations = relations(classes, ({ one, many }) => ({
  school: one(schools, { fields: [classes.schoolId], references: [schools.id] }),
  enrollments: many(enrollments),
  attendanceSessions: many(attendanceSessions),
}));

export const enrollmentsRelations = relations(enrollments, ({ one }) => ({
  student: one(students, { fields: [enrollments.studentId], references: [students.id] }),
  class: one(classes, { fields: [enrollments.classId], references: [classes.id] }),
}));

export const attendanceSessionsRelations = relations(attendanceSessions, ({ one, many }) => ({
  school: one(schools, { fields: [attendanceSessions.schoolId], references: [schools.id] }),
  class: one(classes, { fields: [attendanceSessions.classId], references: [classes.id] }),
  submittedBy: one(staff, { fields: [attendanceSessions.submittedById], references: [staff.id] }),
  records: many(attendanceRecords),
}));

export const attendanceRecordsRelations = relations(attendanceRecords, ({ one }) => ({
  session: one(attendanceSessions, {
    fields: [attendanceRecords.sessionId],
    references: [attendanceSessions.id],
  }),
  student: one(students, { fields: [attendanceRecords.studentId], references: [students.id] }),
}));

export const lessonPlansRelations = relations(lessonPlans, ({ one }) => ({
  school: one(schools, { fields: [lessonPlans.schoolId], references: [schools.id] }),
  teacher: one(staff, { fields: [lessonPlans.teacherId], references: [staff.id], relationName: "lessonPlanTeacher" }),
  reviewer: one(staff, { fields: [lessonPlans.reviewedById], references: [staff.id], relationName: "lessonPlanReviewer" }),
  subject: one(subjects, { fields: [lessonPlans.subjectId], references: [subjects.id] }),
  class: one(classes, { fields: [lessonPlans.classId], references: [classes.id] }),
}));

export const schemesRelations = relations(schemes, ({ one }) => ({
  teacher: one(staff, { fields: [schemes.teacherId], references: [staff.id], relationName: "schemeTeacher" }),
  reviewer: one(staff, { fields: [schemes.reviewedById], references: [staff.id], relationName: "schemeReviewer" }),
  subject: one(subjects, { fields: [schemes.subjectId], references: [subjects.id] }),
  class: one(classes, { fields: [schemes.classId], references: [classes.id] }),
}));

export const examsRelations = relations(exams, ({ many }) => ({
  scores: many(scores),
}));

export const scoresRelations = relations(scores, ({ one }) => ({
  exam: one(exams, { fields: [scores.examId], references: [exams.id] }),
  student: one(students, { fields: [scores.studentId], references: [students.id] }),
  subject: one(subjects, { fields: [scores.subjectId], references: [subjects.id] }),
}));

export const announcementsRelations = relations(announcements, ({ one }) => ({
  createdBy: one(staff, { fields: [announcements.createdById], references: [staff.id] }),
}));

export const notificationsRelations = relations(notifications, ({ one }) => ({
  user: one(users, { fields: [notifications.userId], references: [users.id] }),
}));
